### PR TITLE
Add focus command

### PR DESCRIPTION
**Pull request by scottcorgan**
This adds keycaps and an atom command to focus an already open terminal pane.

If the pane is closed, it does nothing.

### CODE REVIEW

**Comment by scottcorgan** [comment]
@jeremyramin have you had a chance to review?

**Comment by avocade** [comment]
+1

**Comment by taleion** [comment]
Txs @scottcorgan for the first step, would love to go back and forth with the keyboard too !

**Comment by scottcorgan** [comment]
@taleion that's a good point. I'll make that shortcut too. I'm trying to get access to the repo so that I can maintain it.

**Comment by joshuatobin** [comment]
+1 would love to see this merged.

**Comment by 2color** [comment]
Would love to see this merged!

**Comment by ianmurrays** [comment]
👍 would love this! Right now I'm just toggling the terminal on an off 😄

**Comment by dhosterman** [comment]
I'm in the same boat and would absolutely love to be able to change focus via the keyboard!

**Comment by Fred-Barclay** [comment]
@scottcorgan Would you be interested in doing a PR for https://github.com/Fred-Barclay/Termination ? It looks like your code could integrate pretty nicely and I'd be happy to merge it in. :smile:

**Comment by scottcorgan** [comment]
@Fred-Barclay, no need to give me credit. You're welcome to add the functionality. I don't use Atom anymore.

**Comment by Fred-Barclay** [comment]
@scottcorgan Okay, thanks! :)

**Comment by scottcorgan** [comment]
Closing because I no longer use

**Pull request closed without merging**
