### PR TITLE
Fixed collision with jshint

### PR DESCRIPTION
**Pull request by joemckie**

### CODE REVIEW

**Comment by jeremyramin** [comment]
Just so I understand, the class name creates an issue with jshint? If you could provide a screenshot and some additional explanation as to why this is necessary, that would be great.

**Comment by joemckie** [comment]
That's correct, I'm not at my computer right now, but it's reproducible by installing both terminal-plus and jshint.

**Comment by jeremyramin** [comment]
I see where the problem is. Thanks for bringing this issue to my attention. I might want to reorganize the class names myself, if that's alright with you. Otherwise, I'll just merge this and have it in the next release.

**Comment by joemckie** [comment]
No problem, that sounds good to me! I'm surprised it's not the de facto standard for atom packages already, but perhaps a BEM-style approach may be the best way to avoid any collisions?

**Comment by jeremyramin** [comment]
I just had a chance to look at BEM-style. It is interesting, I haven't seen it before. I'll consider this when I go to make the changes.

**Comment by jeremyramin** [comment]
Fixed by PR sindresorhus/atom-jshint#120.

**Pull request closed without merging**
